
function get12hrDisambiguationMode() {
  const buttons = document.getElementsByName('AMPM');
  for (const button of buttons) {
    // There can be only one (radio button chosen).
    if (button.checked) {
      return button.id;
    }
  }
}

function parseSchedule(string, date) {
  return adjustForAMPM(string.split('\n')).map(info => {
    info.resolvesTo = date.hour(info.hour).minute(info.minute);
    return info;
  });
}

function generateOutput(schedule) {
  function getTime(object) {
    return object.resolvesTo.valueOf()/1000;
  }
  const outputLines = [];
  outputLines.push(`**<t:${getTime(schedule[0])}:F>**`);
  outputLines.push(`_(starts at ${schedule[0].resolvesTo.format('h:mma')} ${getTimezone().split('/')[1].replace(/_/g, ' ')} time, but all times are shown by Discord in your own timezone)_`);
  outputLines.push('');
  for (const event of schedule) {
    outputLines.push(`* <t:${getTime(event)}:t> ${event.eventName} (<t:${getTime(event)}:R>)`);
  }
  // TODO: **Date[F]** (first timestamp), _starts at <time> in your timezone <countdown>_, series of times. Discord markup generated by <URL>
  return outputLines.join('\n');
}

function update() {
  const date = getDate();
  if (!date) {
    showDateBlank();
    return;
  } else if (!date.isValid()) {
    showDateError();
    return;
  } else {
    showDateParsed(date);
  }
  try {
    let inputSchedule = document.getElementById('input').value;
    inputSchedule = inputSchedule && inputSchedule.trim() || '';
    const parsedSchedule = inputSchedule && parseSchedule(inputSchedule, date);
    if (!inputSchedule) {
      showScheduleBlank();
    } else if (!parsedSchedule) {
      showScheduleError();
    } else {
      showScheduleParsed(parsedSchedule);
      document.getElementById('output').value = generateOutput(parsedSchedule);
    }
  } catch (e) {
    showScheduleError(e);
  }
}

function showDateBlank() {
  document.getElementById('step1').className = 'ready stepNumber'; // Turn circlular step number red
  let section = document.getElementById('date-result');
  section.innerHTML = ``;
}

function showDateError() {
  document.getElementById('step1').className = 'error stepNumber'; // Turn circlular step number red
  let section = document.getElementById('date-result');
  section.className = 'error result';
  section.innerHTML = `Try one of the following date formats:
    <ul>
    <li>${generateExampleDates().join('<li>')}
  </ul>
  Not all date formats are supported. There are too many, and some invite confusion;
   e.g. 3/4 means March 4 in the U.S. and April 3 in the U.K.
      
      `;
}

function showDateParsed(date) {
  document.getElementById('step1').className = 'success stepNumber'; // Turn circlular step number red
  let section = document.getElementById('date-result');
  section.className = 'success result';
  section.innerHTML = 'aka <b>' + date.format('dddd, D MMMM') + '</b> aka <b>' + date.format('YYYY-MM-DD') + '</b>.';
}


function showScheduleBlank() {
  document.getElementById('step2').className = 'ready stepNumber'; // Turn circlular step number red
  let section = document.getElementById('schedule-result');
  section.innerHTML = ``;
}

function showScheduleError(errorMessage) {
  document.getElementById('step2').className = 'error stepNumber'; // Turn circlular step number red
  let section = document.getElementById('schedule-result');
  section.className = 'error result';
  section.innerHTML = errorMessage ||
      `Make sure each line follows one of the following schedule formats:
    <ul>
    <li>9:30 Event name
    <li>9:30am Event name
    <li>18:30 Event name
    <li>9:30pm Event name
  </ul>
 `;
}


function showScheduleParsed(schedule) {
  document.getElementById('step2').className = 'success stepNumber'; // Turn circlular step number red
  document.getElementById('step3').className = 'ready stepNumber';
  let section = document.getElementById('schedule-result');
  section.className = 'success result';
  const tz = getTimezone();
  const first = schedule[0];
  const last = schedule[schedule.length-1];
  const format1 = "h:mma MMM D";
  const format2 = "YYYY-MM-DD HH:mm";
  section.innerHTML = `
<div>1.                  ${first.resolvesTo.format(format1)} ${tz} (${first.resolvesTo.utc().format(format2)} UTC)</div>
<div>...</div>
<div>${schedule.length}. ${last.resolvesTo.format(format1)} ${tz} (${last.resolvesTo.utc().format(format2)} UTC)</div>
      `;
}

function showCopySuccess() {
  document.getElementById('step3').className = 'success stepNumber';
  document.getElementById('step4').className = 'ready stepNumber';
  let section = document.getElementById('copy-result');
  section.className = 'success result';
  section.innerHTML = `Copied`;
}

function showCopyFailure() {
  document.getElementById('step3').className = 'error stepNumber';
  document.getElementById('step4').className = 'stepNumber';
  let section = document.getElementById('copy-result');
  section.className = 'error result';
  section.innerHTML = `Oops. You'll need to select the text and give a Copy command manually.`;
}

function generateExampleDates() {
  return acceptedDateInputFormats.map((string) => sampleDate.format(string));
}

function getParam(paramName) {
  return new URLSearchParams(window.location.search).get(paramName);
}

function getDefaultTZ() {
  return getParam('defaultTZ') || new Intl.DateTimeFormat().resolvedOptions().timeZone;
}

const tz2part = new Map();

function initializeTZMenu() {
  Intl.supportedValuesOf('timeZone').forEach(name => {
    const [region, city] = name.split('/'); // e.g. 'America', 'Los_Angeles'
    if (!tz2part.has(region)) {
      tz2part.set(region, []);
    }
    tz2part.get(region).push(city);
  });
  setPulldownContents('timezone-region', tz2part.keys(), getDefaultTZ().split('/')[0]);
  populateCitiesFromRegion();
  document.getElementById('timezone-region').addEventListener('change', populateCitiesFromRegion);
  document.getElementById('timezone-region').addEventListener('change', update);
  document.getElementById('timezone-city').addEventListener('change', update);
}

function populateCitiesFromRegion() {
  const selectedRegion = document.getElementById('timezone-region').value;
  setPulldownContents('timezone-city', tz2part.get(selectedRegion), getDefaultTZ().split('/')[1]);
}

function getTimezone() {
  return document.getElementById('timezone-region').value + '/' + document.getElementById('timezone-city').value;
}

function setPulldownContents(pulldownId, contents, defaultValue) {
  const select = document.getElementById(pulldownId);
  select.innerHTML = '';
  for (const item of contents) {
    const option = document.createElement("option");
    option.text = item;
    option.value = item;
    if (item === defaultValue) {
      option.selected = true;
    }
    select.appendChild(option);
  }
}

function initialize() {
  initializeTZMenu();
  document.getElementById('dateField').placeholder = `e.g. "${sampleDate.format('MMMM D')}" will work, or "${sampleDate.format('YYYY-MM-DD')}"`
  update();
}

const defaultDateInputFormat = 'D MMMM YYYY';
const acceptedDateInputFormats = [defaultDateInputFormat, 'MMMM D', 'MMMM D, YYYY', 'D MMMM', 'YYYY-MM-DD'];
const timeLoaded = new dayjs();
const thisYear = timeLoaded.year();
const illAdvisedDefaultYear = new dayjs('Feb 28', 'M D').year();
const sampleDate = new dayjs().startOf('year').endOf('month').hour(12); // hopefully will be reasonable when timezone is off from local

function getDate() {
  let string = document.getElementById('dateField').value;
  let timezone = getTimezone();
  if (string==='') {
    return null;
  }
  try {
    let parsed = dayjs.tz(string, timezone);
    // Default year to this year or next year, whichever is in the future
    if (parsed.year() < thisYear && parsed.year() === illAdvisedDefaultYear) {
      parsed = parsed.year(thisYear);
      if (parsed.diff(timeLoaded) < 0) {
        parsed = parsed.add(1, 'year');
      }
    }
    return parsed;
  } catch {
    return dayjs(string); // will return .isValid()===false but dayjs.tz throws exception
  }
}

function setDate(object) {
  document.getElementById('dateField').value = object.format(defaultDateInputFormat);
  update();
}

function adjust(increment, unit) {
  let current = getDate();
  if (!current || !current.isValid()) current = dayjs.tz().startOf('day');
  setDate(current.add(increment, unit));
}

function setSchedule(content) {
  document.getElementById('input').value = content;
  update();
}

const example = `11:00 morning event
12:00 lunch break
1:30 afternoon event 1
2:30 afternoon event 2`;


function copyOutput() {
  const promise = navigator.clipboard.writeText(document.getElementById('output').value);
  promise.then(showCopySuccess).catch(showCopyFailure);
}

function pasteInput() {
  navigator.clipboard
      .readText()
      .then(
          (clipText) => setSchedule(clipText)
      );
}

// Time logic including implicit am/pm

const timePatterns = {
    numbersOnly: /^(\d?\d):(\d\d) (.*)$/,
    ampm: /^(\d?\d):(\d\d)\ *([ap]\.?m\.?) (.*)$/  // e.g. '1:00pm Lunch break'
  };

function parseTimeRaw(timeAndEvent) {
  // Takes one line, returns {hour, minute, eventName} or throws various exceptions
  timeAndEvent = timeAndEvent.trim();
  const match1 = timeAndEvent.match(timePatterns.ampm);
  if (match1) {
    const [whole, hh, mm, ampm, eventName] = match1;
    let hour = Number(hh);
    let minute = Number(mm);
    const isAM = ampm[0]==='a';
    const isPM = ampm[0]==='p';
    if (hour < 1 || hour > 12) throw timeAndEvent + ' mixes 24-hour time and ' + ampm;
    if (minute > 59) throw timeAndEvent + ' has invalid minute ' + mm;
    switch (hour) {
      case 12: {
        if (isPM) hour = 12; // 12:00pm is noon
        if (isAM) hour = 0; // 12:00am is midight
        break;
      }
      default:
        if (isPM) {
          hour += 12;
        }
    }
    return {hour, minute, eventName};
  }
  const match2 = timeAndEvent.match(timePatterns.numbersOnly);
  if (match2) {
    const [whole, hh, mm, eventName] = match2;
    let hour = Number(hh);
    let minute = Number(mm);
    if (hour > 24) throw `<b>${timeAndEvent}</b>: 24-hour time > 24 hours`;
    if (minute > 60) throw `<b>${timeAndEvent}</b> has invalid minute ${mm}`;
    return {hour, minute, eventName};
  }
  throw `<b>${timeAndEvent}</b> does not have a hh:mm timestamp followed by an event title`;
}

function usesAMPM(sequence) {
  // If I were loading underscore.js I'd use _.every() here.
  for (let timeString of sequence) {
    if (!timeString.match(timePatterns.ampm)) {
      return false;
    }
  }
  return true;
}

function count1200Crossings(rawSequence) {
  let prevHr = -1;
  let prevMin = -1;
  let countCrossings = 0;
  for (let {hour, minute} of rawSequence) {
    if (hour < prevHr || hour===prevHr && minute < prevMin) {
      countCrossings++;
    }
    prevHr = hour;
    prevMin = minute;
  }
  return countCrossings;
}

function adjustFor1200Crossings(rawSequence, initialAdjustment=0) {
  const adjustedSequence = [];
  let adjustment = initialAdjustment;
  let prevHr = -1;
  let prevMin = -1;
  for (let {hour, minute, eventName} of rawSequence) {
    if (hour < prevHr || hour===prevHr && minute < prevMin) {
      adjustment += 12;
    }
    prevHr = hour;
    prevMin = minute;
    adjustedSequence.push({hour: hour + adjustment, minute, eventName});
  }
  return adjustedSequence;
}

function adjustForAMPM(stringSequence, disambiguationMode=get12hrDisambiguationMode()) {
  // returns {hours, ....} times up to 24 hours (or up to 36 if disambiguationMode='startsPM'
  // or throws exception
  let adjustment = 0;
  const rawSequence = stringSequence.map(parseTimeRaw);
  if (disambiguationMode==='guessAMPM' && !usesAMPM(stringSequence)) {
    const countCrossings = count1200Crossings(rawSequence);
    switch (countCrossings) {
      case 0: // guess whether it's all in the afternoon or morning
        if (rawSequence[0].hour >= 9) {
          disambiguationMode = 'startsAM';
        } else {
          disambiguationMode = 'startsPM';
        }
        break;
      case 1: // guess that it crosses noon, not midnight
        disambiguationMode = 'startsAM';
        break;
      default:
        throw `Either keep all events within a day's span to or add am/pm to clarify: this crosses 12:00 ${countCrossings} times!`
    }
  }
  if (disambiguationMode === 'startsPM') {
    adjustment = 12;
  }
  return adjustFor1200Crossings(rawSequence, adjustment);
}